In [4]:
from pathlib import Path
import pandas as pd

from sklearn.preprocessing import StandardScaler

year = 2025

ROOT_DIR = Path.cwd().parent.resolve()

processed_folder = (
    ROOT_DIR
    / "data"
    / "processed"
)

feature_matrix_file = (
    processed_folder
    / f"driver_feature_matrix_{year}.csv"
)

if not feature_matrix_file.exists():

    raise FileNotFoundError(
        f"Could not find "
        f"{feature_matrix_file}"
    )

feature_matrix = pd.read_csv(
    feature_matrix_file
)

print(
    f"Loaded "
    f"{len(feature_matrix)} "
    f"driver profiles"
)

drivers = feature_matrix[
    "Driver"
]

features = feature_matrix.drop(
    columns=["Driver"]
)

print(
    f"Scaling "
    f"{len(features.columns)} "
    f" features"
)

scaler = StandardScaler()

scaled_features = (
    scaler.fit_transform(
        features
    )
)

scaled_feature_matrix = (
    pd.DataFrame(
        scaled_features,
        columns=features.columns
    )
)

scaled_feature_matrix.insert(
    0,
    "Driver",
    drivers
)

print(
    "Scaling complete"
)

Loaded 21 driver profiles
Scaling 12  features
Scaling complete

In [6]:
scaled_feature_matrix.describe()

,RelativePace,PaceStdDev,FastestLapDelta,FullThrottleRatio,BrakeUsageRatio,GearChangeRate,AvgBrakeDistance,AvgEntrySpeed,AvgExitSpeed,AvgSpeedReduction,DegradationRate,PaceDropoff
count,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01,2.100000e+01
mean,2.731149e-14,-8.141636e-16,2.960595e-16,-2.421344e-15,-2.749124e-16,-2.897153e-15,-3.288375e-15,4.993360e-15,2.688326e-15,3.257976e-15,-8.776049e-16,5.709718e-16
std,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00,1.024695e+00
min,-2.053639e+00,-1.785255e+00,-2.123697e+00,-3.737880e+00,-1.808218e+00,-2.683813e+00,-1.276159e+00,-3.221571e+00,-3.655253e+00,-3.277350e+00,-1.425835e+00,-1.315953e+00
25%,-5.446123e-01,-6.781528e-01,-6.394859e-01,-2.328269e-01,-7.691544e-01,-5.326904e-01,-8.190206e-01,-2.059460e-01,-3.090866e-01,-4.894932e-01,-6.308845e-01,-5.303964e-01
50%,3.806416e-01,-1.704170e-01,3.102445e-01,3.770437e-01,-1.259961e-02,7.315262e-02,-1.050681e-01,4.333542e-02,2.604538e-01,-5.852314e-02,-2.153361e-01,-8.348704e-02
75%,7.409164e-01,7.055400e-01,7.918397e-01,5.020481e-01,5.428276e-01,5.360113e-01,4.431793e-01,7.316737e-01,6.003801e-01,8.477935e-01,1.625866e-01,1.981115e-01
max,1.122215e+00,2.346598e+00,1.353435e+00,1.193382e+00,2.276381e+00,1.924640e+00,2.460766e+00,1.714641e+00,1.155181e+00,1.716776e+00,2.687975e+00,3.050592e+00

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(
    scaled_features
)

In [8]:
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=drivers,
    columns=drivers
)

similarity_df.head()

Driver,ALB,ALO,ANT,BEA,BOR,COL,DOO,GAS,HAD,HAM,...,LAW,LEC,NOR,OCO,PIA,RUS,SAI,STR,TSU,VER
Driver,,,,,,,,,,,,,,,,,,,,,
ALB,1.000000,0.422756,-0.226195,0.439139,-0.099242,0.060565,-0.276953,-0.057440,-0.281848,0.249827,...,-0.073657,-0.337108,-0.049478,-0.264167,-0.096493,-0.354933,0.521612,0.283757,0.654103,-0.127534
ALO,0.422756,1.000000,-0.176345,0.469367,0.162142,0.406437,-0.417222,-0.368528,-0.363725,-0.437572,...,-0.432191,0.086697,0.118010,0.147872,-0.291956,-0.002018,-0.241824,0.847950,0.165177,-0.107161
ANT,-0.226195,-0.176345,1.000000,0.234501,0.076153,-0.483638,-0.332637,0.144556,0.387748,0.267042,...,0.004835,-0.037101,-0.051513,0.116568,0.407432,0.379090,0.019982,-0.089175,-0.557203,-0.368300
BEA,0.439139,0.469367,0.234501,1.000000,-0.260394,0.311836,-0.750418,0.337988,0.361263,0.131950,...,-0.198058,-0.180584,-0.038257,-0.118666,-0.036667,-0.076302,0.180283,0.380796,0.322862,-0.317321
BOR,-0.099242,0.162142,0.076153,-0.260394,1.000000,-0.122777,0.481087,-0.042322,-0.106376,-0.131001,...,0.286979,-0.418413,-0.710973,0.589081,-0.611805,-0.410059,0.043971,0.482069,-0.445096,-0.684228

In [9]:
similarity_df.round(2)

Driver,ALB,ALO,ANT,BEA,BOR,COL,DOO,GAS,HAD,HAM,...,LAW,LEC,NOR,OCO,PIA,RUS,SAI,STR,TSU,VER
Driver,,,,,,,,,,,,,,,,,,,,,
ALB,1.00,0.42,-0.23,0.44,-0.10,0.06,-0.28,-0.06,-0.28,0.25,...,-0.07,-0.34,-0.05,-0.26,-0.10,-0.35,0.52,0.28,0.65,-0.13
ALO,0.42,1.00,-0.18,0.47,0.16,0.41,-0.42,-0.37,-0.36,-0.44,...,-0.43,0.09,0.12,0.15,-0.29,-0.00,-0.24,0.85,0.17,-0.11
ANT,-0.23,-0.18,1.00,0.23,0.08,-0.48,-0.33,0.14,0.39,0.27,...,0.00,-0.04,-0.05,0.12,0.41,0.38,0.02,-0.09,-0.56,-0.37
BEA,0.44,0.47,0.23,1.00,-0.26,0.31,-0.75,0.34,0.36,0.13,...,-0.20,-0.18,-0.04,-0.12,-0.04,-0.08,0.18,0.38,0.32,-0.32
BOR,-0.10,0.16,0.08,-0.26,1.00,-0.12,0.48,-0.04,-0.11,-0.13,...,0.29,-0.42,-0.71,0.59,-0.61,-0.41,0.04,0.48,-0.45,-0.68
COL,0.06,0.41,-0.48,0.31,-0.12,1.00,0.08,-0.13,-0.05,-0.69,...,-0.23,0.00,-0.02,0.22,-0.56,-0.22,-0.48,0.31,0.48,-0.04
DOO,-0.28,-0.42,-0.33,-0.75,0.48,0.08,1.00,-0.07,-0.19,-0.31,...,0.50,-0.34,-0.47,0.30,-0.45,-0.41,-0.05,-0.24,-0.02,-0.19
GAS,-0.06,-0.37,0.14,0.34,-0.04,-0.13,-0.07,1.00,0.68,0.33,...,0.74,-0.61,-0.48,-0.39,0.00,-0.26,0.52,-0.24,0.21,-0.41
HAD,-0.28,-0.36,0.39,0.36,-0.11,-0.05,-0.19,0.68,1.00,0.23,...,0.36,-0.15,-0.40,0.05,-0.07,-0.16,0.13,-0.26,-0.08,-0.35
HAM,0.25,-0.44,0.27,0.13,-0.13,-0.69,-0.31,0.33,0.23,1.00,...,0.09,-0.10,-0.06,-0.21,0.38,-0.13,0.74,-0.29,-0.14,0.01
HUL,-0.56,0.02,-0.10,-0.03,0.21,0.56,0.23,0.19,0.30,-0.65,...,0.11,0.01,-0.18,0.16,-0.39,0.12,-0.60,0.08,-0.09,-0.18
LAW,-0.07,-0.43,0.00,-0.20,0.29,-0.23,0.50,0.74,0.36,0.09,...,1.00,-0.77,-0.67,-0.22,-0.19,-0.44,0.49,-0.27,0.18,-0.47
LEC,-0.34,0.09,-0.04,-0.18,-0.42,0.00,-0.34,-0.61,-0.15,-0.10,...,-0.77,1.00,0.78,0.07,0.36,0.63,-0.64,-0.15,-0.31,0.78
NOR,-0.05,0.12,-0.05,-0.04,-0.71,-0.02,-0.47,-0.48,-0.40,-0.06,...,-0.67,0.78,1.00,-0.43,0.70,0.79,-0.41,-0.23,0.04,0.88
OCO,-0.26,0.15,0.12,-0.12,0.59,0.22,0.30,-0.39,0.05,-0.21,...,-0.22,0.07,-0.43,1.00,-0.65,-0.40,-0.32,0.41,-0.50,-0.41
PIA,-0.10,-0.29,0.41,-0.04,-0.61,-0.56,-0.45,0.00,-0.07,0.38,...,-0.19,0.36,0.70,-0.65,1.00,0.75,0.11,-0.47,-0.15,0.55
RUS,-0.35,-0.00,0.38,-0.08,-0.41,-0.22,-0.41,-0.26,-0.16,-0.13,...,-0.44,0.63,0.79,-0.40,0.75,1.00,-0.51,-0.27,-0.30,0.56
SAI,0.52,-0.24,0.02,0.18,0.04,-0.48,-0.05,0.52,0.13,0.74,...,0.49,-0.64,-0.41,-0.32,0.11,-0.51,1.00,-0.04,0.23,-0.32
STR,0.28,0.85,-0.09,0.38,0.48,0.31,-0.24,-0.24,-0.26,-0.29,...,-0.27,-0.15,-0.23,0.41,-0.47,-0.27,-0.04,1.00,-0.12,-0.41
TSU,0.65,0.17,-0.56,0.32,-0.45,0.48,-0.02,0.21,-0.08,-0.14,...,0.18,-0.31,0.04,-0.50,-0.15,-0.30,0.23,-0.12,1.00,0.12
VER,-0.13,-0.11,-0.37,-0.32,-0.68,-0.04,-0.19,-0.41,-0.35,0.01,...,-0.47,0.78,0.88,-0.41,0.55,0.56,-0.32,-0.41,0.12,1.00

In [10]:
all_similarity = []

for driver in similarity_df.index:

    similarities = (
        similarity_df.loc[driver]
        .drop(driver)
        .sort_values(
            ascending=False
        )
    )

    top_match = similarities.index[0]
    score = similarities.iloc[0]

    all_similarity.append(
        {
            "Driver": driver,
            "MostSimilarDriver": top_match,
            "SimilarityScore": score
        }
    )

driver_similarity = pd.DataFrame(
    all_similarity
)

driver_similarity

   Driver MostSimilarDriver  SimilarityScore
0     ALB               TSU         0.654103
1     ALO               STR         0.847950
2     ANT               PIA         0.407432
3     BEA               ALO         0.469367
4     BOR               OCO         0.589081
5     COL               HUL         0.557774
6     DOO               LAW         0.502126
7     GAS               LAW         0.744874
8     HAD               GAS         0.678161
9     HAM               SAI         0.741726
10    HUL               COL         0.557774
11    LAW               GAS         0.744874
12    LEC               NOR         0.779559
13    NOR               VER         0.876527
14    OCO               BOR         0.589081
15    PIA               RUS         0.749533
16    RUS               NOR         0.794126
17    SAI               HAM         0.741726
18    STR               ALO         0.847950
19    TSU               ALB         0.654103
20    VER               NOR         0.876527

In [11]:
driver_similarity.sort_values(
    "SimilarityScore",
    ascending=False
)

   Driver MostSimilarDriver  SimilarityScore
20    VER               NOR         0.876527
13    NOR               VER         0.876527
18    STR               ALO         0.847950
1     ALO               STR         0.847950
16    RUS               NOR         0.794126
12    LEC               NOR         0.779559
15    PIA               RUS         0.749533
11    LAW               GAS         0.744874
7     GAS               LAW         0.744874
9     HAM               SAI         0.741726
17    SAI               HAM         0.741726
8     HAD               GAS         0.678161
0     ALB               TSU         0.654103
19    TSU               ALB         0.654103
14    OCO               BOR         0.589081
4     BOR               OCO         0.589081
5     COL               HUL         0.557774
10    HUL               COL         0.557774
6     DOO               LAW         0.502126
3     BEA               ALO         0.469367
2     ANT               PIA         0.407432

In [12]:
similarity_df.loc["VER"] \
    .sort_values(
        ascending=False
    ) \
    .head(6)

Driver
VER    1.000000
NOR    0.876527
LEC    0.776072
RUS    0.556515
PIA    0.545140
TSU    0.116243
Name: VER, dtype: float64

In [13]:
similarity_df.loc["NOR"] \
    .sort_values(
        ascending=False
    ) \
    .head(6)

Driver
NOR    1.000000
VER    0.876527
RUS    0.794126
LEC    0.779559
PIA    0.699876
ALO    0.118010
Name: NOR, dtype: float64